RUN_SBT = sbt

APP_NAME = scala-project-template
APP_VERSION = 1.0.0-SNAPSHOT

envfile ?= .env.example

.env:
	cp -f $(envfile) .env

compile:
	$(RUN_SBT) compile

build:
	$(RUN_SBT) docker:publishLocal

test:
	$(RUN_SBT) test

run:
	docker run --rm --env-file .env --name $(APP_NAME) $(APP_NAME):$(APP_VERSION)